# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s100fgga676-1Q

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.cache/wt} [current_project]
set_property parent.project_path {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/adams/Desktop/Final Year Project/CPU/ALU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Add2InBit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Add4.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder16_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder1_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder2_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder32_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder4_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder8_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AluMux1.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate16_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate1_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate2_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate32_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate4_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/AndGate8_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ControlUnits.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/FillLow0.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Final.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/FlagZero.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/InstrMem.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/InstrMemory.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Memory.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveFH.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveFL.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveFromHi.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveFromLow.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveTH.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveTL.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveToHigh.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MoveToLow.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Mux32In.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Mux4InBit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Mux5BitIn.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MuxHalf.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MuxTwoIn.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NandGate.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NandGate16.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NandGate2.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NandGate32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NandGate4.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NandGate8.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate16_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate1_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate2_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate32_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate4_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NorGate8_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate1.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate16.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate2.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate4.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/NotGate8.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate1.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate16.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate2.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate4.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/OrGate8.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ProgramCounter.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/RegisterFile.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SLThen.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SLThenU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SetLessThen.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SetLessThenU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftLLV.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftLLV32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRAV.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRAV32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRL.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRLV.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRLV32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SignExt.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SignExtension.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SimpleMMU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/TwoInMux.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/UnAdder.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/UnSub.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/UnSubtract32_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/WriteRegSelect.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate1.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate16.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate2.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate4.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/XorGate8.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ZeroExt.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ZeroFlag.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/nnnn.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/W.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/M.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/E.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/D.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ContUnit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SetGrtThen.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/P_RegisterFile.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/P_FullALU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/P_ALU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Comparator.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MipsPipelining.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/P_ProgramCount.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Pipelining.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MUX3In.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Mux8In.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Mips.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/FPAddSub.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Mux24In.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SRL24In.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Add24Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Add24_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder12_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder6_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Adder3_Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SllSrl24.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Add9Bits.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Sub9Bit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/PipeliningExternalMemory.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/TopLevelView.vhd}
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/DataMem.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ALU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ControlUnit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/DataMem1.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/DataPath.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/F_StageReg.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/FullALU.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Immediate4.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/JumpInstr.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/MipsSingleCycleProcessor.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ProgramCount.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftLL.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftLL32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRA.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRA32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ShiftRL32.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SingleCyclePro.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/SingleCycleProcessor.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/E_StageReg.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/M_StageReg.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/W_StageReg.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/HazardUnit.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Reg_File.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/P_Reg_File.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/HandLReg.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/ExponentDiff.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/Rounding.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/PipeliningProcessor.vhd}
  {C:/Users/adams/Desktop/Final Year Project/CPU/ALU.srcs/sources_1/new/PipeliningDataPath.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TopLevelView -part xc7s100fgga676-1Q


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TopLevelView.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TopLevelView_utilization_synth.rpt -pb TopLevelView_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
